name: Cleanup Old Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: freenet-actions/delete-old-releases@v3.0.0
        with:
          max-age: "P1M"
          dry-run: true
          delete-tags: true
          token: ${{ github.token }}
